name: app_design
description: app_design
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  widgetbook: ^3.10.0
  widgetbook_annotation: ^3.2.0

  widget:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  dart_code_linter: ^1.1.3
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.9.0

flutter:
  uses-material-design: true
