name: Deploy App Design

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-app-design:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            packages/widget

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ github.token }}
          filters: |
            widget-changes:
              - 'packages/widget/**'

      - name: Set Up Melos
        if: github.event_name == 'workflow_dispatch' || steps.filter.outputs.widget-changes == 'true'
        uses: ./.github/actions/set_up_melos
        with:
          working-directory: ./

      - name: Install dependencies
        if: github.event_name == 'workflow_dispatch' || steps.filter.outputs.widget-changes == 'true'
        working-directory: packages/widget/app_design
        run: flutter pub get

      - name: Run Flutter build App Design
        if: github.event_name == 'workflow_dispatch' || steps.filter.outputs.widget-changes == 'true'
        working-directory: packages/widget/app_design
        run: flutter build web --target=lib/widgetbook.dart

      - name: Deploy App Design
        if: github.event_name == 'workflow_dispatch' || steps.filter.outputs.widget-changes == 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.XSERVER_HOST }}
          username: ${{ secrets.XSERVER_FTP_USER }}
          password: ${{ secrets.XSERVER_FTP_PASSWORD }}
          local-dir: ./packages/widget/app_design/build/web/
          server-dir: /ucs-design.net/public_html/melos_sample_ui_catalog/